import { formatDate, formatDateTime, formatUsd, type Cents, type Iso, type Load, type LoadStop } from '@truckdesk/shared';

/**
 * Document generation: rate confirmation, BOL, POD, invoice.
 *
 * Primary renderer is pdfme (MIT). pdfme needs fonts registered per document,
 * and it is loaded dynamically so that a Worker bundle without pdfme simply
 * falls through to the built-in writer below rather than failing at import
 * time. The fallback emits a valid, if plain, PDF with no dependencies at all -
 * so `POST /loads/:id/bol` works in a cold Worker, in Docker, and in tests.
 */

export type DocumentKind = 'rate_con' | 'bol' | 'pod' | 'invoice' | 'settlement';

export interface PdfRenderOptions {
  kind: DocumentKind;
  title: string;
  subtitle?: string;
  /** Left column: label/value pairs. Right column: the same. */
  sections: PdfSection[];
  table?: PdfTable;
  footer?: string;
  /** Signature block, for POD and settlement. */
  signature?: { name?: string; signedAt?: Iso; capturedAt?: Iso };
}

export interface PdfSection {
  title?: string;
  fields: Array<{ label: string; value: string }>;
  /** Render a whole section at normal weight instead of bold. */
  compact?: boolean;
}

export interface PdfTable {
  columns: Array<{ label: string; width: number; align?: 'left' | 'right' | 'center' }>;
  rows: string[][];
  /** Drawn in bold above the totals rows. */
  totals?: Array<{ label: string; value: string }>;
}

export interface RenderedDocument {
  bytes: Uint8Array;
  mimeType: 'application/pdf';
  fileName: string;
  renderer: 'pdfme' | 'builtin';
}

export const PAGE_WIDTH_PT = 612; // US Letter at 72dpi
export const PAGE_HEIGHT_PT = 792;
const MARGIN_PT = 48;

/* -------------------------------------------------------------------------- */
/* Entry points                                                                  */
/* -------------------------------------------------------------------------- */

export async function renderRateConfirmation(input: {
  load: Load;
  companyName: string;
  companyMcNumber?: string;
  companyAddress?: string;
  driverName?: string;
  truckUnit?: string;
  totalCents?: Cents;
}): Promise<RenderedDocument> {
  const { load } = input;
  const stops = load.stops ?? [];

  return render({
    kind: 'rate_con',
    title: 'Rate Confirmation',
    subtitle: `${load.broker} · ${load.reference ?? load.id}`,
    sections: [
      {
        title: 'Load',
        fields: [
          { label: 'Load ID', value: load.id },
          { label: 'Broker', value: load.broker },
          { label: 'Commodity', value: load.commodity ?? '-' },
          { label: 'Equipment', value: load.equipment ?? 'dry van' },
          { label: 'Weight', value: load.weightLbs ? `${load.weightLbs.toLocaleString()} lbs` : '-' },
          { label: 'Miles', value: String(load.miles) },
        ],
      },
      {
        title: 'Schedule',
        fields: [
          { label: 'Pickup', value: formatDateTime(load.pickupDate) },
          { label: 'Delivery', value: formatDateTime(load.deliveryDate) },
          { label: 'Pickup window', value: load.pickupWindow ? windowLabel(load.pickupWindow) : '-' },
          { label: 'Delivery window', value: load.deliveryWindow ? windowLabel(load.deliveryWindow) : '-' },
          { label: 'Driver', value: input.driverName ?? '-' },
          { label: 'Truck', value: input.truckUnit ?? '-' },
        ],
      },
      {
        title: 'Carrier',
        fields: [
          { label: 'Carrier', value: input.companyName },
          { label: 'MC', value: input.companyMcNumber ?? '-' },
          { label: 'Address', value: input.companyAddress ?? '-' },
        ],
      },
    ],
    table: stops.length > 0
      ? {
          columns: [
            { label: 'Seq', width: 0.08 },
            { label: 'Type', width: 0.14 },
            { label: 'Facility', width: 0.4 },
            { label: 'City', width: 0.22 },
            { label: 'State', width: 0.16, align: 'center' },
          ],
          rows: stops
            .slice()
            .sort((a, b) => a.sequence - b.sequence)
            .map((stop) => [
              String(stop.sequence),
              stop.type,
              stop.facilityName,
              `${stop.city}`,
              stop.state,
            ]),
        }
      : undefined,
    footer: `Rate ${formatUsd(load.rate)} over ${load.miles} miles (${formatUsd(
      load.miles > 0 ? Math.round(load.rate / load.miles) : 0,
    )}/mi). Generated by TruckDesk.`,
  });
}

export async function renderBol(input: {
  load: Load;
  companyName: string;
  companyMcNumber?: string;
  driverName?: string;
  truckUnit?: string;
  sealed?: boolean;
  exceptions?: string[];
}): Promise<RenderedDocument> {
  const { load } = input;
  const stops = load.stops ?? [];

  return render({
    kind: 'bol',
    title: 'Bill of Lading',
    subtitle: `${load.broker} · ${load.reference ?? load.id}`,
    sections: [
      {
        title: 'Shipment',
        fields: [
          { label: 'Load ID', value: load.id },
          { label: 'Broker', value: load.broker },
          { label: 'Commodity', value: load.commodity ?? '-' },
          { label: 'Pieces', value: load.weightLbs ? `${load.weightLbs.toLocaleString()} lbs` : '-' },
          { label: 'Trailer', value: load.equipment ?? 'dry van' },
          { label: 'Seal', value: input.sealed === false ? 'SEAL BROKEN' : 'Sealed' },
        ],
      },
      {
        title: 'Carrier',
        fields: [
          { label: 'Carrier', value: input.companyName },
          { label: 'MC', value: input.companyMcNumber ?? '-' },
          { label: 'Driver', value: input.driverName ?? '-' },
          { label: 'Truck', value: input.truckUnit ?? '-' },
        ],
      },
    ],
    table: stops.length > 0
      ? {
          columns: [
            { label: 'Seq', width: 0.08 },
            { label: 'Type', width: 0.14 },
            { label: 'Facility', width: 0.4 },
            { label: 'City', width: 0.22 },
            { label: 'State', width: 0.16, align: 'center' },
          ],
          rows: stops
            .slice()
            .sort((a, b) => a.sequence - b.sequence)
            .map((stop) => [String(stop.sequence), stop.type, stop.facilityName, stop.city, stop.state]),
        }
      : undefined,
    signature: {
      name: input.driverName,
      signedAt: load.pickedUpAt,
    },
    footer: input.exceptions?.length
      ? `EXCEPTIONS NOTED: ${input.exceptions.join('; ')}`
      : 'No exceptions noted at time of pickup.',
  });
}

export async function renderPod(input: {
  load: Load;
  companyName: string;
  driverName?: string;
  receiverName?: string;
  signatureDataUrl?: string;
  signatureName?: string;
  exceptions?: string[];
  photos?: Array<{ fileName: string; capturedAt?: Iso }>;
}): Promise<RenderedDocument> {
  const { load } = input;
  const stops = (load.stops ?? []).filter((stop) => stop.type === 'delivery');
  const deliveredStop = stops[0];

  return render({
    kind: 'pod',
    title: 'Proof of Delivery',
    subtitle: `${load.broker} · ${load.reference ?? load.id}`,
    sections: [
      {
        title: 'Delivery',
        fields: [
          { label: 'Delivered at', value: formatDateTime(load.deliveredAt) },
          { label: 'Facility', value: deliveredStop?.facilityName ?? load.destination },
          { label: 'Pieces received', value: load.weightLbs ? `${load.weightLbs.toLocaleString()} lbs` : '-' },
          { label: 'Trailer', value: load.equipment ?? 'dry van' },
          { label: 'Driver', value: input.driverName ?? '-' },
          { label: 'Receiver', value: input.receiverName ?? input.signatureName ?? '-' },
        ],
      },
      {
        title: 'Carrier',
        fields: [{ label: 'Carrier', value: input.companyName }],
      },
    ],
    table:
      input.photos && input.photos.length > 0
        ? {
            columns: [
              { label: 'Photo', width: 0.6 },
              { label: 'Captured', width: 0.4, align: 'right' },
            ],
            rows: input.photos.map((photo) => [
              photo.fileName,
              formatDateTime(photo.capturedAt),
            ]),
          }
        : undefined,
    signature: {
      name: input.signatureName ?? input.receiverName,
      signedAt: load.deliveredAt,
    },
    footer: input.exceptions?.length
      ? `EXCEPTIONS: ${input.exceptions.join('; ')}`
      : 'Freight received in good order with no exceptions.',
  });
}

export async function renderInvoice(input: {
  invoiceNumber: string;
  brokerName: string;
  issuedAt: Iso;
  dueAt: Iso;
  termsDays: number;
  lines: Array<{ description: string; kind: string; miles: number; amountCents: Cents }>;
  subtotalCents: Cents;
  taxCents: Cents;
  totalCents: Cents;
  amountPaidCents: Cents;
  balanceCents: Cents;
  companyName: string;
  companyAddress?: string
  companyMcNumber?: string;
  notes?: string;
}): Promise<RenderedDocument> {
  return render({
    kind: 'invoice',
    title: `Invoice ${input.invoiceNumber}`,
    subtitle: input.brokerName,
    sections: [
      {
        title: 'Bill to',
        fields: [{ label: 'Broker', value: input.brokerName }],
      },
      {
        title: 'From',
        fields: [
          { label: 'Carrier', value: input.companyName },
          { label: 'MC', value: input.companyMcNumber ?? '-' },
          { label: 'Address', value: input.companyAddress ?? '-' },
        ],
      },
      {
        title: 'Terms',
        fields: [
          { label: 'Issued', value: formatDate(input.issuedAt) },
          { label: 'Due', value: formatDate(input.dueAt) },
          { label: 'Terms', value: `Net ${input.termsDays}` },
        ],
      },
    ],
    table: {
      columns: [
        { label: 'Description', width: 0.52 },
        { label: 'Miles', width: 0.16, align: 'right' },
        { label: 'Amount', width: 0.32, align: 'right' },
      ],
      rows: input.lines.map((line) => [
        line.description,
        line.miles > 0 ? String(line.miles) : '-',
        formatUsd(line.amountCents),
      ]),
      totals: [
        { label: 'Subtotal', value: formatUsd(input.subtotalCents) },
        ...(input.taxCents > 0 ? [{ label: 'Tax', value: formatUsd(input.taxCents) }] : []),
        { label: 'Total', value: formatUsd(input.totalCents) },
        ...(input.amountPaidCents > 0
          ? [{ label: 'Paid', value: formatUsd(input.amountPaidCents) }]
          : []),
        { label: 'Balance due', value: formatUsd(input.balanceCents) },
      ],
    },
    footer: input.notes ?? 'Thank you for your business.',
  });
}

/* -------------------------------------------------------------------------- */
/* Renderer selection                                                            */
/* -------------------------------------------------------------------------- */

/**
 * Try pdfme first. If it is not present in this runtime (a slim Worker bundle,
 * a cold edge isolate) fall back to the built-in writer. The returned
 * `renderer` field says which path ran, and tests assert on it.
 */
export async function render(options: PdfRenderOptions): Promise<RenderedDocument> {
  const pdfme = await loadPdfme().catch(() => null);
  if (pdfme) {
    try {
      const bytes = await renderWithPdfme(pdfme, options);
      return {
        bytes,
        mimeType: 'application/pdf',
        fileName: fileNameFor(options),
        renderer: 'pdfme',
      };
    } catch {
      // Fall through: a pdfme schema mismatch should never fail a POD.
    }
  }

  return {
    bytes: renderBuiltin(options),
    mimeType: 'application/pdf',
    fileName: fileNameFor(options),
    renderer: 'builtin',
  };
}

export function fileNameFor(options: PdfRenderOptions): string {
  const slug = options.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
  return `${slug}.pdf`;
}

/* -------------------------------------------------------------------------- */
/* pdfme path                                                                    */
/* -------------------------------------------------------------------------- */

interface PdfmeModule {
  PDFDocument: new (config: unknown) => { addText: (ops: unknown[]) => Promise<unknown>; save: () => Promise<ArrayBuffer> };
  StandardFonts: { Helvetica: string; HelveticaBold: string };
}

let pdfmePromise: Promise<PdfmeModule | null> | null = null;

async function loadPdfme(): Promise<PdfmeModule | null> {
  if (!pdfmePromise) {
    pdfmePromise = (async () => {
      try {
        const moduleName = 'pdfme';
        const imported = (await import(/* @vite-ignore */ moduleName)) as Record<string, unknown>;
        const PDFDocument = imported['PDFDocument'] as PdfmeModule['PDFDocument'] | undefined;
        const StandardFonts = imported['StandardFonts'] as PdfmeModule['StandardFonts'] | undefined;
        if (!PDFDocument || !StandardFonts) return null;
        return { PDFDocument, StandardFonts };
      } catch {
        return null;
      }
    })();
  }
  return pdfmePromise;
}

const FONT_REGULAR = 'Helvetica';
const FONT_BOLD = 'Helvetica-Bold';

async function renderWithPdfme(
  pdfme: PdfmeModule,
  options: PdfRenderOptions,
): Promise<Uint8Array> {
  const doc = new pdfme.PDFDocument({
    pdfVersion: '1.7',
    pageSize: { width: PAGE_WIDTH_PT, height: PAGE_HEIGHT_PT },
    margins: { top: MARGIN_PT, bottom: MARGIN_PT, left: MARGIN_PT, right: MARGIN_PT },
    fonts: {
      [FONT_REGULAR]: { data: '', fontName: FONT_REGULAR },
      [FONT_BOLD]: { data: '', fontName: FONT_BOLD },
    },
  });

  const ops = layoutToPdfmeOps(options, pdfme.StandardFonts);
  await doc.addText(ops);
  const buffer = await doc.save();
  return new Uint8Array(buffer);
}

/** Convert the layout model into pdfme text/rect draw operations. */
function layoutToPdfmeOps(options: PdfRenderOptions, fonts: PdfmeModule['StandardFonts']): unknown[] {
  const ops: unknown[] = [];
  const contentWidth = PAGE_WIDTH_PT - MARGIN_PT * 2;
  let y = MARGIN_PT;

  const text = (
    value: string,
    x: number,
    yPos: number,
    width: number,
    size: number,
    fontName: string,
    align: 'left' | 'center' | 'right' = 'left',
  ) => {
    ops.push({
      text: value.slice(0, Math.max(8, Math.floor(width / (size * 0.5)))),
      x,
      y: yPos,
      width,
      fontSize: size,
      fontName,
      color: '#111111',
      ...(align === 'center' ? { alignment: 'center' } : {}),
      ...(align === 'right' ? { alignment: 'right' } : {}),
    });
  };

  const rect = (x: number, yPos: number, width: number, height: number, color: string) => {
    ops.push({
      rectangle: { x, y: yPos, width, height },
      color,
      borderWidth: 0,
    });
  };

  /* header */
  text(options.title, MARGIN_PT, y, contentWidth, 20, fonts.HelveticaBold);
  y += 26;
  if (options.subtitle) {
    text(options.subtitle, MARGIN_PT, y, contentWidth, 10, fonts.Helvetica);
    y += 16;
  }
  rect(MARGIN_PT, y, contentWidth, 1, '#d4d4d8');
  y += 18;

  /* sections, two columns */
  const columnWidth = (contentWidth - 24) / 2;
  const sectionRows = Math.max(
    1,
    ...options.sections.map((section) => section.fields.length + (section.title ? 2 : 0)),
  );

  for (let index = 0; index < options.sections.length; index += 1) {
    const section = options.sections[index];
    if (!section) continue;
    const column = index % 2;
    const row = Math.floor(index / 2);
    const x = MARGIN_PT + column * (columnWidth + 24);
    const startY = y + row * (sectionRows * 16 + 16);

    let localY = startY;
    if (section.title) {
      text(section.title.toUpperCase(), x, localY, columnWidth, 8, fonts.HelveticaBold);
      localY += 14;
    }
    for (const field of section.fields) {
      text(field.label, x, localY, columnWidth * 0.42, 8, fonts.Helvetica);
      text(field.value, x + columnWidth * 0.42, localY, columnWidth * 0.58, 8, fonts.HelveticaBold);
      localY += 13;
    }
  }

  y += sectionRows * 16 + 28;

  /* table */
  if (options.table) {
    const widths = options.table.columns.map((column) => column.width * contentWidth);
    let x = MARGIN_PT;

    options.table.columns.forEach((column, index) => {
      const width = widths[index] ?? 0;
      const align = column.align ?? 'left';
      text(
        column.label.toUpperCase(),
        align === 'right' ? x + width - 80 : x,
        y,
        Math.min(width, 80),
        8,
        fonts.HelveticaBold,
        align,
      );
      x += width;
    });
    y += 6;
    rect(MARGIN_PT, y, contentWidth, 0.75, '#a1a1aa');
    y += 12;

    for (const row of options.table.rows) {
      let cellX = MARGIN_PT;
      row.forEach((cell, index) => {
        const width = widths[index] ?? 0;
        const align = options.table?.columns[index]?.align ?? 'left';
        text(String(cell), align === 'right' ? cellX + width - 90 : cellX, y, Math.min(width, 90), 8, fonts.Helvetica, align);
        cellX += width;
      });
      y += 13;
    }

    if (options.table.totals && options.table.totals.length > 0) {
      y += 8;
      rect(MARGIN_PT, y, contentWidth, 0.75, '#a1a1aa');
      y += 12;
      for (const total of options.table.totals) {
        text(total.label, MARGIN_PT + contentWidth - 260, y, 160, 8, fonts.Helvetica);
        text(total.value, MARGIN_PT + contentWidth - 100, y, 100, 8, fonts.HelveticaBold, 'right');
        y += 13;
      }
    }
  }

  /* signature */
  if (options.signature) {
    y = Math.max(y + 32, PAGE_HEIGHT_PT - 220);
    rect(MARGIN_PT, y, 260, 0.75, '#3f3f46');
    text(
      `Signature: ${options.signature.name ?? '________________'}`,
      MARGIN_PT,
      y + 8,
      260,
      8,
      fonts.Helvetica,
    );
    text(`Date: ${formatDateTime(options.signature.signedAt)}`, MARGIN_PT, y + 22, 260, 8, fonts.Helvetica);
  }

  /* footer */
  if (options.footer) {
    text(
      options.footer,
      MARGIN_PT,
      PAGE_HEIGHT_PT - MARGIN_PT,
      contentWidth,
      8,
      fonts.Helvetica,
    );
  }

  return ops;
}

/* -------------------------------------------------------------------------- */
/* Built-in writer                                                               */
/* -------------------------------------------------------------------------- */

/**
 * Minimal PDF writer, no dependencies. Produces a valid single-page document
 * using the standard Helvetica fonts that every reader has built in. It exists
 * so that document generation never becomes an outage: no pdfme, no font
 * upload, no template JSON.
 */
export function renderBuiltin(options: PdfRenderOptions): Uint8Array {
  const lines: string[] = [];
  lines.push(`TruckDesk - ${options.title}`);
  if (options.subtitle) lines.push(options.subtitle);
  lines.push('');

  for (const section of options.sections) {
    if (section.title) {
      lines.push(section.title.toUpperCase());
      for (const field of section.fields) {
        lines.push(`  ${field.label}: ${field.value}`);
      }
      lines.push('');
    } else {
      for (const field of section.fields) lines.push(`  ${field.label}: ${field.value}`);
    }
  }

  if (options.table) {
    for (const row of options.table.rows) lines.push(`  ${row.join('  |  ')}`);
    if (options.table.totals) {
      for (const total of options.table.totals) {
        lines.push(`  ${total.label}: ${total.value}`);
      }
    }
    lines.push('');
  }

  if (options.signature) {
    lines.push('');
    lines.push(`  Signature: ${options.signature.name ?? ''}`);
    lines.push(`  Date: ${options.signature.signedAt ?? ''}`);
  }

  if (options.footer) {
    lines.push('');
    lines.push(options.footer);
  }

  // PDF 1.4 text-only document: catalogue, pages, page, font, content stream.
  const content = [
    'BT',
    '/F1 9 Tf',
    `${MARGIN_PT} ${PAGE_HEIGHT_PT - MARGIN_PT} Td`,
    `${leadingFor(lines.length)} TL`,
    ...lines.flatMap((line) => [escapePdfText(line), 'T*']),
    'ET',
  ].join('\n');

  const objects: string[] = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH_PT} ${PAGE_HEIGHT_PT}] ` +
      '/Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',
    `<< /Length ${content.length} >>\nstream\n${content}\nendstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>',
  ];

  let pdf = '%PDF-1.4\n';
  const offsets: number[] = [];

  objects.forEach((body, index) => {
    offsets.push(pdf.length);
    pdf += `${index + 1} 0 obj\n${body}\nendobj\n`;
  });

  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const offset of offsets) {
    pdf += `${offset.toString().padStart(10, '0')} 00000 n \n`;
  }
  pdf +=
    `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\n` +
    `startxref\n${xrefOffset}\n%%EOF\n`;

  return new TextEncoder().encode(pdf);
}

function leadingFor(lineCount: number): number {
  // Compress leading when the content would overflow one page.
  return lineCount > 60 ? 9 : lineCount > 44 ? 11 : 13;
}

function escapePdfText(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
}

function windowLabel(window: { start: Iso; end: Iso }): string {
  return `${formatDate(window.start)} - ${formatDate(window.end)}`;
}

/** Stop summary used by the BOL header block. */
export function stopSummary(stops: readonly LoadStop[]): string {
  return stops
    .slice()
    .sort((a, b) => a.sequence - b.sequence)
    .map((stop) => `${stop.sequence}. ${stop.type} ${stop.facilityName}, ${stop.city} ${stop.state}`)
    .join(' | ');
}